ALTER TABLE "communities"
ADD COLUMN "primaryColor" TEXT NOT NULL DEFAULT '#4f46e5',
ADD COLUMN "accentColor" TEXT NOT NULL DEFAULT '#9333ea',
ADD COLUMN "themeStyle" TEXT NOT NULL DEFAULT 'GRADIENT';
