export const PRODUCT_EVENTS = {
  ACCOUNT_REGISTERED: 'ACCOUNT_REGISTERED',
  SESSION_ACTIVE: 'SESSION_ACTIVE',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  COMMUNITY_JOINED: 'COMMUNITY_JOINED',
  COMMUNITY_JOIN_REQUESTED: 'COMMUNITY_JOIN_REQUESTED',
  EVENT_REGISTERED: 'EVENT_REGISTERED',
  OPPORTUNITY_SAVED: 'OPPORTUNITY_SAVED',
  OPPORTUNITY_APPLIED: 'OPPORTUNITY_APPLIED',
  STUDENT_FOLLOWED: 'STUDENT_FOLLOWED',
  POST_CREATED: 'POST_CREATED',
  MESSAGE_SENT: 'MESSAGE_SENT',
} as const;

export type ProductEvent = (typeof PRODUCT_EVENTS)[keyof typeof PRODUCT_EVENTS];

export const ACTIVATION_EVENTS: ProductEvent[] = [
  PRODUCT_EVENTS.COMMUNITY_JOINED,
  PRODUCT_EVENTS.COMMUNITY_JOIN_REQUESTED,
  PRODUCT_EVENTS.EVENT_REGISTERED,
  PRODUCT_EVENTS.OPPORTUNITY_SAVED,
  PRODUCT_EVENTS.OPPORTUNITY_APPLIED,
  PRODUCT_EVENTS.STUDENT_FOLLOWED,
  PRODUCT_EVENTS.POST_CREATED,
  PRODUCT_EVENTS.MESSAGE_SENT,
];
